### ISSUE TITLE
100 files with >100 lines output don't find error in 2nd line of files

### ISSUE THREAD

**Issue by rubek** [SamirTalwar/Smoke#4] opened 2016-07-07 17:23 UTC
I generated test cases for the uglytrivia shellscript game (you know it: https://github.com/jbrains/trivia) with the following command/script:
# !/bin/bash

for I in {0..100};
do echo $I;
    echo SEED=$I ./game.sh > test/game$I.in
    SEED=$I ./game.sh > test/game$I.out
done

Anytime I open one of the .out files, add "asdf" as the second line (creative, I know) and run "smoke '/bin/bash' test/", it tells me that 100 tests succeeded even though they shouldn't have.

If I add any other line, the test usually failed as expected in my trying out.

**Comment by SamirTalwar** [comment] 2016-07-10 10:21
I tried it but couldn't reproduce it. Could you take a look at [the trivia branch](https://github.com/SamirTalwar/Smoke/tree/trivia) I just pushed and see if you can?

You can run it with:

    bin/smoke fixtures/trivia.sh fixtures/trivia

**Comment by codecop** [comment] 2016-07-17 18:11
By reading about `Open3.popen3`, I found it might hang for large output/inputs. Maybe this is the case here. It seems to be recommended to use Open3.capture3 instead.

**Comment by SamirTalwar** [comment] 2017-10-09 00:41
Well, I've done a ground-up rewrite in https://github.com/SamirTalwar/Smoke/pull/8, so the odds of this still happening are low. (It's probably been replaced by new, shinier bugs!)

I'm going to close it. Feel free to reopen it if it's still a problem.

**Closed by SamirTalwar** 2017-10-09 00:41 UTC
