### ISSUE TITLE
qemu aarch64 build fail 

### ISSUE THREAD

**Issue by ivan19871002** [SamirTalwar/smoke#100] opened 2023-02-21 05:35 UTC
text-icu> configure
text-icu> Configuring text-icu-0.8.0.2...
text-icu> Cabal-simple_SvXsv1f__3.6.3.0_ghc-9.2.5: The program 'pkg-config' version
text-icu> >=0.9.0 is required but it could not be found.
text-icu>
Progress 1/2

Error: [S-7282]
       Stack failed to execute the build plan.

       While executing the build plan, Stack encountered the following errors:

       [S-7011]
       While building package text-icu-0.8.0.2 (scroll up to its section to see the error) using:

qemu : ubuntu 20.04.5 lts  aarch64
kernel linux version 5.10.146
already install libicu-dev

**Comment by SamirTalwar** [comment] 2023-02-21 23:08
I reverted regex support and removed text-icu in #97, so this should be fixed. Please feel free to re-open this if you can still reproduce the issue on the latest `main`.

**Closed by SamirTalwar** 2023-02-21 23:08 UTC

**Comment by ivan19871002** [comment] 2023-02-22 01:26
I need regex support. it is ok when we build on x86_x64 . it is build fail on mac and aarch64

**Comment by SamirTalwar** [comment] 2023-02-22 09:27
OK, that's good to know! Unfortunately most regular expression packages for Haskell require dynamic dependencies that break on certain OS/arch combinations.

Do you think you'd be happy with POSIX support? I am thinking of reintroducing it with [regex-tdfa]. If you could take a look at that library and let me know if it fits your purposes, it'll help me decide.

[regex-tdfa]: https://github.com/haskell-hvr/regex-tdfa

**Comment by ivan19871002** [comment] 2023-02-22 10:44
if i checkout this commit 2ee73564bf28896ddb8f6cbb117a78b663c77d3e. ghc version is 9.0.2, text-iuc version is 0.7.1.0
It is ok on aarch64, So if I want enable regex on the latest main,  what's lib  that i need install . 
@SamirTalwar 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~
https://github.com/haskell-hvr/regex-tdfa/issues/3   I think this bug is a big problem .
My smoke test is runing on  arm64 board. little memory .I'm worried that the performance will degrade and the program won't be able to continue

**Comment by SamirTalwar** [comment] 2023-02-22 21:28
Oh, thanks for finding that issue. That's not an option, then.

There is no regex support on `main` any more; I have removed it for now, because I can't get it to reliably build across operating systems. You can check out a previous version but you'll get the same problem as before.

I suggest we carry on this discussion in #69. I'll re-open it.
